import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Calendar, Flame, Zap, Award, CheckCircle2, ChevronRight, Sparkles, HeartPulse, Compass } from 'lucide-react';
import { TrainingPlanData, TrainingDayPlan } from '../types.ts';

interface TrainingPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  plan: TrainingPlanData | null;
  onLogWorkout?: (dayPlan: TrainingDayPlan) => void;
}

export const TrainingPlanModal: React.FC<TrainingPlanModalProps> = ({
  isOpen,
  onClose,
  plan,
  onLogWorkout,
}) => {
  if (!isOpen || !plan) return null;

  const getWorkoutBadgeColor = (type: string) => {
    switch (type) {
      case 'Intervals':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
      case 'Tempo Run':
        return 'bg-rose-500/10 text-rose-400 border-rose-500/30';
      case 'Long Run':
        return 'bg-purple-500/10 text-purple-400 border-purple-500/30';
      case 'Recovery':
      case 'Easy Run':
        return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
      default:
        return 'bg-slate-500/10 text-slate-400 border-slate-500/30';
    }
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm overflow-y-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="relative w-full max-w-4xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden my-8"
        >
          {/* Header Banner */}
          <div className="relative p-6 sm:p-8 bg-gradient-to-r from-emerald-950/60 via-slate-900 to-indigo-950/50 border-b border-slate-800">
            <button
              id="close-plan-modal-btn"
              onClick={onClose}
              className="absolute top-5 right-5 p-2 rounded-xl text-slate-400 hover:text-slate-100 hover:bg-slate-800/80 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-2 mb-3">
              <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                <Sparkles className="w-3.5 h-3.5" />
                Auto-Generated by Pasiya Agent (Gemini 2.5 Flash)
              </span>
              <span className="text-xs text-slate-400 font-mono">
                {plan.weekStarting}
              </span>
            </div>

            <h2 className="text-2xl sm:text-3xl font-bold text-slate-100 tracking-tight flex items-center gap-3">
              <span>7-Day Autonomous Training Plan</span>
            </h2>

            <p className="mt-2 text-sm sm:text-base text-slate-300 max-w-2xl leading-relaxed">
              {plan.coachSummary}
            </p>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-6 pt-4 border-t border-slate-800/80">
              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
                <div className="text-xs text-slate-400 font-medium">Weekly Target Volume</div>
                <div className="text-xl font-bold text-emerald-400 font-mono mt-0.5">
                  {plan.weeklyTargetKm} km
                </div>
              </div>
              <div className="bg-slate-950/60 p-3 rounded-xl border border-slate-800">
                <div className="text-xs text-slate-400 font-medium">Key Priority Sessions</div>
                <div className="text-sm font-semibold text-slate-200 mt-1 truncate">
                  {plan.keyWorkouts?.length || 2} Workouts
                </div>
              </div>
              <div className="col-span-2 sm:col-span-1 bg-slate-950/60 p-3 rounded-xl border border-slate-800">
                <div className="text-xs text-slate-400 font-medium">Auto Dispatch Mode</div>
                <div className="text-sm font-semibold text-indigo-400 mt-1 flex items-center gap-1">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  Monday 6:00 AM Cron
                </div>
              </div>
            </div>
          </div>

          {/* Daily Schedule Cards */}
          <div className="p-6 sm:p-8 space-y-4 max-h-[60vh] overflow-y-auto">
            <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
              <Calendar className="w-4 h-4 text-emerald-400" />
              Day-by-Day Microcycle
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {plan.days?.map((day, idx) => (
                <div
                  key={idx}
                  className="bg-slate-950/70 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-slate-700 transition-all group"
                >
                  <div>
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <span className="font-bold text-slate-200 group-hover:text-emerald-400 transition-colors">
                        {day.day}
                      </span>
                      <span
                        className={`text-xs px-2.5 py-0.5 rounded-full font-medium border ${getWorkoutBadgeColor(
                          day.workoutType
                        )}`}
                      >
                        {day.workoutType}
                      </span>
                    </div>

                    <div className="flex items-center gap-4 text-sm text-slate-300 font-mono mb-2">
                      {day.distanceKm > 0 ? (
                        <>
                          <span className="font-bold text-slate-100">{day.distanceKm} km</span>
                          <span className="text-slate-400">@ {day.targetPace}</span>
                        </>
                      ) : (
                        <span className="text-slate-400">Rest & Recovery Day</span>
                      )}
                    </div>

                    <div className="text-xs font-semibold text-emerald-400/90 mb-1">
                      {day.focus}
                    </div>
                    <p className="text-xs text-slate-400 leading-relaxed">
                      {day.instructions}
                    </p>
                  </div>

                  {onLogWorkout && day.distanceKm > 0 && (
                    <div className="mt-4 pt-3 border-t border-slate-900 flex justify-end">
                      <button
                        id={`log-day-${idx}-btn`}
                        onClick={() => {
                          onLogWorkout(day);
                          onClose();
                        }}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-emerald-600 text-slate-200 hover:text-white transition-all"
                      >
                        Log to Run Logbook
                        <ChevronRight className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Recovery & Nutrition Advice */}
            {plan.recoveryTip && (
              <div className="mt-6 p-4 rounded-xl bg-indigo-950/30 border border-indigo-500/30 flex items-start gap-3">
                <HeartPulse className="w-5 h-5 text-indigo-400 shrink-0 mt-0.5" />
                <div>
                  <div className="text-xs font-bold uppercase tracking-wider text-indigo-300">
                    Coach Recovery & Fueling Directive
                  </div>
                  <p className="text-sm text-slate-300 mt-1">
                    {plan.recoveryTip}
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Footer Actions */}
          <div className="p-4 sm:p-6 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
            <span className="text-xs text-slate-500">
              Generated by Google Gemini 2.5 Flash • Zero Cloud Cost (Free Tier)
            </span>
            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-sm font-semibold transition-colors"
            >
              Close Plan
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}; 
